version: "3"

services:
    client:
        build: .
        hostname: deployment_client
        image: pedropozuelo/linuxctf:latest
        volumes:
            - ./src:/usr/share/nginx/html
        ports:
          - "0.0.0.0:80:80"
